name: fullstack

services:
  mongo:
    image: mongo:8.0.9
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE: chaicode
    networks:
      - fullstack-network

  redis:
    image: redis:alpine
    container_name: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    environment:
      - REDIS_USER: ${REDIS_USER}
      - REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - fullstack-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
    - ./backend/.env
    depends_on:
      - mongo
      - redis
    networks:
      - fullstack-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
    - ./frontend/.env
    depends_on:
      - backend
    networks:
      - fullstack-network


volumes:
  mongo-data:
  redis-data:

networks:
  fullstack-network:
