services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - fullstack-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - fullstack-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8081:8080"
    env_file:
    - ./backend/.env
    depends_on:
      - mongo
      - redis
    networks:
      - fullstack-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
    - ./frontend/.env
    depends_on:
      - backend
    networks:
      - fullstack-network


volumes:
  mongo-data:

networks:
  fullstack-network:
